apiVersion: v1
kind: Service
metadata:
  name: snack-mm-bot
  namespace: snack-mm-bot
  labels:
    app: snack-mm-bot
spec:
  selector:
    app: snack-mm-bot
  ports:
    - name: snack-mm-bot-port
      port: 8080
      protocol: TCP
      targetPort: 8080
