name: Build and Deploy
on:
  push:
    branches:
      - master

env:
  DO_REGISTRY: isaw-registry

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - run: |-
          doctl registry login --expiry-seconds=600

      - name: Docker build
        run: |-
          docker build -f Dockerfile \
            --tag "registry.digitalocean.com/$DO_REGISTRY/snack-mm-bot:$GITHUB_SHA" \
            .

      - name: Publish to registry
        run: |-
          docker push "registry.digitalocean.com/$DO_REGISTRY/snack-mm-bot:$GITHUB_SHA"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: matootie/dokube@v1.3.4
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: snack-k8s

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy
        run: |-
          alias kustomize=$(realpath ./kustomize)
          cd _deploy
          kustomize edit set image registry.digitalocean.com/$DO_REGISTRY/snack-mm-bot:TAG=registry.digitalocean.com/$DO_REGISTRY/snack-mm-bot:$GITHUB_SHA
          kustomize build . | kubectl apply -f -
          kubectl get services -o wide
